name = "ShapML"
uuid = "8523bd24-6f66-414b-9e1e-b02db3916d64"
repo = "https://github.com/nredell/ShapML.jl.git"
authors = ["Nickalus Redell"]
version = "0.3.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
julia = "1"
DataFrames = "^0.21, ^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
